# Generated by Django 4.1.7 on 2023-05-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
