# Generated by Django 4.1.7 on 2023-05-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_models_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='models',
            name='uuid',
            field=models.CharField(default='', max_length=255),
        ),
    ]
